### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by pedrxu** [RisingOrange/anki-mindmap#1]
"Erro
Ocorreu um erro. Por favor, inicie o Anki enquanto segura a tecla shift, isto vai desabilitar temporariamente as extensões que você instalou.
Se o problema ocorrer somente quando as extensões são habilitadas, use o Ferramentas > Extensões para desabilitar algumas extensões e reinicie o Anki, repetindo até descobrir a extensão que está causando o problema.
Quando você descobrir a extensão que está causando o problema, por favor reporte o problema em site de suporte de extensão.
Informações de Depuração:" <- It is portuguese 

Erro
Ocorreu um erro. Por favor, inicie o Anki enquanto segura a tecla shift, isto vai desabilitar temporariamente as extensões que você instalou.
Se o problema ocorrer somente quando as extensões são habilitadas, use o Ferramentas > Extensões para desabilitar algumas extensões e reinicie o Anki, repetindo até descobrir a extensão que está causando o problema.
Quando você descobrir a extensão que está causando o problema, por favor reporte o problema em site de suporte de extensão.
Informações de Depuração:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.12.6 PyQt 5.12.3
Platform: Windows 7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-02-27 18:48:26
When i tried to create a new map, i got this:
Caught exception:
Traceback (most recent call last):
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\mindmap_creator_dialog.py", line 68, in _on_button_click
    mindmap.save_as_img(
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\mindmap.py", line 19, in save_as_img
    create_mindmap_img(tree_to_markdown(tree), output_file_path, theme)
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\_vendor\brain_dump\graphviz.py", line 78, in create_mindmap_img
    graph = parse_text_graph(graph_markdown, root_label=root_label)
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\_vendor\brain_dump\parsers\indented_text_graph.py", line 18, in parse
    raise ValueError('Line {} is empty'.format(i + 1))
ValueError: Line 2 is empty

**Comment by RisingOrange** [comment]
I published an update that should fix the error. Does it work for you?

**Comment by pedrxu** [comment]
Unfortunally not.

Erro
Ocorreu um erro. Por favor, inicie o Anki enquanto segura a tecla shift, isto vai desabilitar temporariamente as extensões que você instalou.
Se o problema ocorrer somente quando as extensões são habilitadas, use o Ferramentas > Extensões para desabilitar algumas extensões e reinicie o Anki, repetindo até descobrir a extensão que está causando o problema.
Quando você descobrir a extensão que está causando o problema, por favor reporte o problema em site de suporte de extensão.
Informações de Depuração:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.12.6 PyQt 5.12.3
Platform: Windows 7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-02-27 18:48:26

Caught exception:
Traceback (most recent call last):
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\mindmap_creator_dialog.py", line 68, in _on_button_click
    mindmap.save_as_img(
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\mindmap.py", line 17, in save_as_img
    create_mindmap_img(
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\_vendor\brain_dump\graphviz.py", line 97, in create_mindmap_img
    graph = parse_text_graph(graph_markdown, root_label=root_label)
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\_vendor\brain_dump\parsers\indented_text_graph.py", line 20, in parse
    raise ValueError(
ValueError: Incorrect indentation on line 2: not a mutiple of 4 spaces

**Comment by RisingOrange** [comment]
Hm, I think you don't have the newest version yet. I updated it today and in the output you sent it says:
``Add-ons, last update check: 2021-02-27 18:48:26``

Try going to Tools->Addons->Check for Updates

Anyway, if it still doesn't work just send me the output again, I added some more info to the error message that should help find the cause of the problem.

**Comment by pedrxu** [comment]
> 
> 
> Hm, I think you don't have the newest version yet. I updated it today and in the output you sent it says:
> `Add-ons, last update check: 2021-02-27 18:48:26`
> 
> Try going to Tools->Addons->Check for Updates
> 
> Anyway, if it still doesn't work just send me the output again, I added some more info to the error message that should help find the cause of the problem.

I guess is my PC or something

"Erro
Ocorreu um erro. Por favor, inicie o Anki enquanto segura a tecla shift, isto vai desabilitar temporariamente as extensões que você instalou.
Se o problema ocorrer somente quando as extensões são habilitadas, use o Ferramentas > Extensões para desabilitar algumas extensões e reinicie o Anki, repetindo até descobrir a extensão que está causando o problema.
Quando você descobrir a extensão que está causando o problema, por favor reporte o problema em site de suporte de extensão.
Informações de Depuração:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.12.6 PyQt 5.12.3
Platform: Windows 7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-02-27 18:48:26

Caught exception:
Traceback (most recent call last):
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\_vendor\pydot\pydot.py", line 1886, in create
    stdout_data, stderr_data, process = call_graphviz(
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\_vendor\pydot\pydot.py", line 124, in call_graphviz
    process = subprocess.Popen(
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1307, in _execute_child
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\mindmap_creator_dialog.py", line 68, in _on_button_click
    mindmap.save_as_img(
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\mindmap.py", line 17, in save_as_img
    create_mindmap_img(
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\_vendor\brain_dump\graphviz.py", line 112, in create_mindmap_img
    pygraph.write_svg(output_file_path)
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\_vendor\pydot\pydot.py", line 1706, in new_method
    self.write(
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\_vendor\pydot\pydot.py", line 1791, in write
    s = self.create(prog, format, encoding=encoding)
  File "C:\Users\HASSAN\AppData\Roaming\Anki2\addons21\965278890\_vendor\pydot\pydot.py", line 1896, in create
    raise OSError(*args)
FileNotFoundError: [WinError 2] "dot" not found in path."

**Comment by RisingOrange** [comment]
Ok, I think I know what's the problem. Do you have Graphviz installed? I have mentioned it on the Ankiweb page, but I should probably make it more clear that it is needed. 

You can download an installer from https://graphviz.org/download/. Scroll to Windows and download one of the installers from there. When asked if you want to add graphviz to the PATH, choose "Add to the path for all users".

**Comment by pedrxu** [comment]
> 
> 
> Ok, I think I know what's the problem. Do you have Graphviz installed? I have mentioned it on the Ankiweb page, but I should probably make it more clear that it is needed.
> 
> You can download an installer from https://graphviz.org/download/. Scroll to Windows and download one of the installers from there. When asked if you want to add graphviz to the PATH, choose "Add to the path for all users".

Thank you! It worked. When I installed graphviz, I did just for the current user and now I installed for all users. Thanks

**Comment by RisingOrange** [comment]
Great! I am glad it works now. 
I will add the information that you need to install it for all users to the instructions. Thanks for mentioning this.

**Comment by todeoe** [comment]
> hello, I'm with the same problem, I ready did the installations of the Graphviz, but don't fix the problem, do you can help me?



> Great! I am glad it works now. I will add the information that you need to install it for all users to the instructions. Thanks for mentioning this.


I have the same problem, I did as instructed but it still persists, I am a Windows user.

below the error:

Erro
Ocorreu um erro. Por favor, inicie o Anki enquanto segura a tecla shift, isto vai desabilitar temporariamente as extensões que você instalou.
Se o problema ocorrer somente quando as extensões são habilitadas, use o Ferramentas > Extensões para desabilitar algumas extensões e reinicie o Anki, repetindo até descobrir a extensão que está causando o problema.
Quando você descobrir a extensão que está causando o problema, por favor reporte o problema em site de suporte de extensão.
Informações de Depuração:
Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
Platform: Windows-10-10.0.19044
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-01-04 22:17:44

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 43, in cmd
  File "aqt.webview", line 150, in _onCmd
  File "aqt.webview", line 620, in _onBridgeCmd
  File "aqt.editor", line 469, in onBridgeCmd
  File "C:\Users\jeff\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\common.py", line 121, in _show
    self._instance = self._target.constructor(
  File "C:\Users\jeff\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\generator.py", line 670, in _init_
    super(EditorGenerator, self)._init_(
  File "C:\Users\jeff\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 243, in _init_
    super(ServiceDialog, self)._init_(*args, **kwargs)
  File "C:\Users\jeff\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 80, in _init_
    self.setLayout(self._ui())
  File "C:\Users\jeff\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 255, in _ui
    hor.addLayout(self._ui_services())
  File "C:\Users\jeff\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 313, in _ui_services
    layout.addLayout(self._ui_services_presets())
  File "C:\Users\jeff\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\base.py", line 340, in _ui_services_presets
    save.setFixedWidth(save.fontMetrics().width(save.text()) + 20)
AttributeError: 'QFontMetrics' object has no attribute 'width

**Comment by gustavobarbosa-p** [comment]
> I have the same problem, I did as instructed but it still persists, I am a Windows user.

Did you manage to solve the problem? I am also having the same error in the AwesomeTTS extension.
