### ISSUE TITLE
cannot import name 'MutableSequence' from 'collections'

### ISSUE THREAD

**Issue by GrimPixel** [RisingOrange/anki-mindmap#10]
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Mindmap from tag hierarchy⁩':
⁨Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/aqt/addons.py", line 239, in loadAddons
import(addon.dir_name)
File "/home/grim/.local/share/Anki2/addons21/965278890/init.py", line 13, in
from .mindmap_creator_dialog import show as show_dialog
File "/home/grim/.local/share/Anki2/addons21/965278890/mindmap_creator_dialog.py", line 12, in
from .libaddon.gui.dialog_webview import WebViewer
File "/home/grim/.local/share/Anki2/addons21/965278890/libaddon/gui/dialog_webview.py", line 42, in
from .basic.dialog_basic import BasicDialog
File "/home/grim/.local/share/Anki2/addons21/965278890/libaddon/gui/basic/dialog_basic.py", line 40, in
from .interface import CommonWidgetInterface
File "/home/grim/.local/share/Anki2/addons21/965278890/libaddon/gui/basic/interface.py", line 48, in
from collections import MutableSequence, MutableSet, MutableMapping
ImportError: cannot import name 'MutableSequence' from 'collections' (/usr/lib/python3.10/collections/init.py)

**Comment by RisingOrange** [comment]
I uploaded an update to the add-on which should fix this.
