### ISSUE TITLE
TypeError: C++ type 'QWebEngineDownloadItem*' is not supported as a pyqtSlot argument type

### ISSUE THREAD

**Issue by GrimPixel** [RisingOrange/anki-mindmap#13]
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Mindmap from tag hierarchy⁩':
⁨Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/addons.py", line 244, in loadAddons
    __import__(addon.dir_name)
  File "/home/grim/.local/share/Anki2/addons21/965278890/__init__.py", line 13, in <module>
    from .mindmap_creator_dialog import show as show_dialog
  File "/home/grim/.local/share/Anki2/addons21/965278890/mindmap_creator_dialog.py", line 12, in <module>
    from .libaddon.gui.dialog_webview import WebViewer
  File "/home/grim/.local/share/Anki2/addons21/965278890/libaddon/gui/dialog_webview.py", line 47, in <module>
    class WebViewer(BasicDialog):
  File "/home/grim/.local/share/Anki2/addons21/965278890/libaddon/gui/dialog_webview.py", line 89, in WebViewer
    @pyqtSlot("QWebEngineDownloadItem*")
TypeError: C++ type 'QWebEngineDownloadItem*' is not supported as a pyqtSlot argument type
⁩

**Comment by MVilj** [comment]
I am getting this same error on both, desktop and laptop with newest versions of both anki and graphviz

**Comment by MVilj** [comment]
> [worksforme] comment out this line for it to work
> 
> https://github.com/RisingOrange/anki-mindmap/blob/dd3eaa8c198fa4abe40b480f625941210462ed86/src/mindmap/libaddon/gui/dialog_webview.py#L89
> 
> 
> `C:\Users\%username%\AppData\Roaming\Anki2\addons21\965278890\libaddon\gui\dialog_webview.py:89`
> ```python
> #    @pyqtSlot("QWebEngineDownloadItem*")
> ```

The error went away and it shows in the addons menu, but its still missing from anki. There is no button or option anywhere to create the mindmap
