### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by envoy221b** [RisingOrange/anki-mindmap#15]
Hello, I purchased a new laptop and my older settings are gone and i'm having trouble installing the add on again :( 
this is the problem I am facing 
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.2.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-08-22 10:31:13
Add-ons possibly involved: ⁨Mindmap from tag hierarchy⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/anshika/Library/Application Support/Anki2/addons21/965278890/mindmap_creator_dialog.py", line 48, in _on_show_button_click
    self._export_image_mindmap(f.name)
  File "/Users/anshika/Library/Application Support/Anki2/addons21/965278890/mindmap_creator_dialog.py", line 151, in _export_image_mindmap
    raise e
  File "/Users/anshika/Library/Application Support/Anki2/addons21/965278890/mindmap_creator_dialog.py", line 134, in _export_image_mindmap
    mindmap.save_as_img(
  File "/Users/anshika/Library/Application Support/Anki2/addons21/965278890/mindmap.py", line 46, in save_as_img
    raise e
  File "/Users/anshika/Library/Application Support/Anki2/addons21/965278890/mindmap.py", line 35, in save_as_img
    create_mindmap_img(
  File "/Users/anshika/Library/Application Support/Anki2/addons21/965278890/_vendor/brain_dump/graphviz.py", line 112, in create_mindmap_img
    pygraph.write_svg(output_file_path, prog=pydot_program, encoding='utf-8')
  File "/Users/anshika/Library/Application Support/Anki2/addons21/965278890/_vendor/pydot/pydot.py", line 1609, in new_method
    self.write(
  File "/Users/anshika/Library/Application Support/Anki2/addons21/965278890/_vendor/pydot/pydot.py", line 1691, in write
    s = self.create(prog, format, encoding=encoding)
  File "/Users/anshika/Library/Application Support/Anki2/addons21/965278890/_vendor/pydot/pydot.py", line 1785, in create
    stdout_data, stderr_data, process = call_graphviz(
  File "/Users/anshika/Library/Application Support/Anki2/addons21/965278890/_vendor/pydot/pydot.py", line 129, in call_graphviz
    process = subprocess.Popen(
  File "subprocess", line 951, in __init__
  File "subprocess", line 1821, in _execute_child
PermissionError: [Errno 13] Permission denied: '/opt/homebrew/opt/graphviz'

Please help me out with this. 
Thankyou so much

**Comment by envoy221b** [comment]
I remembered how I did it before and solved the problem. I literally wasn't pointing to the dot file in the path. Extremely silly. But it's solved now and I can finally start using the add on again. It's incredible. Thank you so much!!

**Comment by sleepyboi420** [comment]
> I remembered how I did it before and solved the problem. I literally wasn't pointing to the dot file in the path. Extremely silly. But it's solved now and I can finally start using the add on again. It's incredible. Thank you so much!!

could you please tell me what you did to solve the problem and how exactly you "pointed to the dot" file?

thank you
