### ISSUE TITLE
Error- exception

### ISSUE THREAD

**Issue by iterating** [RisingOrange/anki-mindmap#3]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-04-12 17:52:54

Caught exception:
Traceback (most recent call last):
  File "C:\Users\jy\AppData\Roaming\Anki2\addons21\965278890\mindmap_creator_dialog.py", line 93, in _on_show_button_click
    self._save_mindmap_to_file(f.name)
  File "C:\Users\jy\AppData\Roaming\Anki2\addons21\965278890\mindmap_creator_dialog.py", line 125, in _save_mindmap_to_file
    mindmap.save_as_img(
  File "C:\Users\jy\AppData\Roaming\Anki2\addons21\965278890\mindmap.py", line 17, in save_as_img
    create_mindmap_img(
  File "C:\Users\jy\AppData\Roaming\Anki2\addons21\965278890\_vendor\brain_dump\graphviz.py", line 117, in create_mindmap_img
    pygraph.write_svg(output_file_path)
  File "C:\Users\jy\AppData\Roaming\Anki2\addons21\965278890\_vendor\pydot\pydot.py", line 1705, in new_method
    self.write(
  File "C:\Users\jy\AppData\Roaming\Anki2\addons21\965278890\_vendor\pydot\pydot.py", line 1790, in write
    s = self.create(prog, format, encoding=encoding)
  File "C:\Users\jy\AppData\Roaming\Anki2\addons21\965278890\_vendor\pydot\pydot.py", line 1867, in create
    self.write(tmp_name, encoding=encoding)
  File "C:\Users\jy\AppData\Roaming\Anki2\addons21\965278890\_vendor\pydot\pydot.py", line 1788, in write
    f.write(s)
  File "C:\python\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 33946-33947: character maps to <undefined>

**Comment by RisingOrange** [comment]
Hello @iterating, I updated the add-on and it should work now. I would appreciate it if you could try it again and tell me if the problem is solved.

**Comment by iterating** [comment]
It's fixed, the ad-on works great now. Thank you!
